name: paulhemmings.com
favicon: null
layout_spectrum: 0.34597027115523815
typography_spectrum: 0.9060347699560225
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6559425839222968
  lightness: 0.659327904926613
  saturation: 0.6662707426585257
  rhythmicContrast: 0.8449640437029302
purpose: []
